[profile.default]
src = "src"
out = "out"
libs = [
    "../../node_modules"
]
allow_paths = [
    "../../node_modules"
]
fs_permissions = [
    { access = "read", path = "./" },
    { access = "read", path = "../../node_modules" }
]
optimizer = true
optimizer_runs = 200
#compiler.version = "0.8.27+commit.40a35a09"
#evm_version = "paris"
